version: '3'

networks:
  app-tier:
    driver: bridge

services:
  postgres: 
    image: postgres:16.2-alpine3.19
    networks:
      - app-tier
    restart: always
    env_file:
      - ./.env
    ports:
      - 5436:5439
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: dockerfile
    image: todo-api:latest
    networks:
      - app-tier
    restart: always
    env_file:
      - ./.env
    ports:
      - 8080:8080

volumes:
  pg_data:
